name: css
channels:
  - conda-forge
dependencies:
  - python=3.10
  - scipy
  - pip
  - numpy
  - matplotlib
  - tqdm
  - pandas
  - seaborn
  - pytest
  - jupyter
  - cvxpy
  - scs
  - Cython
  - rpy2
  - pingouin 
  - pip:
    - -r requirements.txt
    - git+https://github.com/jcrudy/choldate.git